name: Build and deploy ASP.Net Core app to Azure Web App - allseedcrm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # ✅ จำเป็นสำหรับใช้ OIDC Authentication
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ED2F2B3FB1F44B0B91BC5D770264A7C3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9DA4CA3D187A41C998995523877DBF2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A6363B6705149CD9C2536CC1B03FAE4 }}
          audience: api://AzureADTokenExchange   # ✅ เพิ่มพารามิเตอร์นี้เพื่อรองรับ OIDC Authentication

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'allseedcrm'
          slot-name: 'Production'
          package: ./myapp
